Docs: remove fedora in openvas-smb
openvas-smb is not buildable with fedora anymore as the used heimdal
versions are too new.

This results in:
```
6.71 /workspaces/greenbone/openvas-smb/samba/auth/credentials/credentials_krb5.c: In function 'cli_credentials_set_from_ccache':
26.71 /workspaces/greenbone/openvas-smb/samba/auth/credentials/credentials_krb5.c:102:9: warning: 'krb5_princ_realm' is deprecated: Use X instead [-Wdeprecated-declarations]
26.71   102 |         realm = krb5_princ_realm(cred->ccache->smb_krb5_context->krb5_context, princ);
26.71       |         ^~~~~
26.71 In file included from /usr/include/heimdal/krb5.h:967,
26.71                  from /workspaces/greenbone/openvas-smb/samba/lib/replace/system/kerberos.h:133,
26.71                  from /workspaces/greenbone/openvas-smb/samba/auth/credentials/credentials_krb5.c:33:
26.71 /usr/include/heimdal/krb5-protos.h:6374:1: note: declared here
26.71  6374 | krb5_princ_realm (
26.71       | ^~~~~~~~~~~~~~~~
26.72 /workspaces/greenbone/openvas-smb/samba/auth/credentials/credentials_krb5.c: In function 'cli_credentials_get_client_gss_creds':
26.72 /workspaces/greenbone/openvas-smb/samba/auth/credentials/credentials_krb5.c:316:20: error: implicit declaration of function 'gss_krb5_import_cred'; did you mean 'gss_import_cred'? [-Wimplicit-function-declaration]
26.72   316 |         maj_stat = gss_krb5_import_cred(&min_stat, ccache->ccache, NULL, NULL,
26.72       |                    ^~~~~~~~~~~~~~~~~~~~
26.72       |                    gss_import_cred
26.72 /workspaces/greenbone/openvas-smb/samba/auth/credentials/credentials_krb5.c: In function 'cli_credentials_set_client_gss_creds':
26.72 /workspaces/greenbone/openvas-smb/samba/auth/credentials/credentials_krb5.c:367:20: error: implicit declaration of function 'gss_krb5_copy_ccache' [-Wimplicit-function-declaration]
26.72   367 |         maj_stat = gss_krb5_copy_ccache(&min_stat,
26.72       |                    ^~~~~~~~~~~~~~~~~~~~
26.72 gmake[2]: *** [samba/CMakeFiles/samba-static.dir/build.make:1470: samba/CMakeFiles/samba-static.dir/auth/credentials/credentials_krb5.c.o] Error 1
26.72 gmake[1]: *** [CMakeFiles/Makefile2:136: samba/CMakeFiles/samba-static.dir/all] Error 2
26.72 gmake: *** [Makefile:156: all] Error 2
```

when tested on fedora:latest -> fedora 41.

The test code is as follows:
```
RUN bash /source/.devcontainer/github-clone.sh greenbone/openvas-smb
RUN dnf install -y \
  glib2-devel \
  gnutls-devel \
  popt-devel \
  mingw64-gcc \
  libunistring-devel \
  heimdal-devel \
  perl \
  # missing on docs
  libcom_err-devel
RUN PKG_CONFIG_PATH="/usr/lib64/heimdal/lib/pkgconfig:${PKG_CONFIG_PATH}" \
	sh /source/.devcontainer/build-cmake-project.sh /workspaces/greenbone/openvas-smb
```

github-clone.sh can be found at:
https://github.com/greenbone/openvas-scanner/blob/dc44a8aa89e8016d09d6398ec80972e66d862aa1/.devcontainer/github-clone.sh

build-cmake-project can be found at:
https://github.com/greenbone/openvas-scanner/blob/dc44a8aa89e8016d09d6398ec80972e66d862aa1/.devcontainer/build-cmake-project.sh